server:
  port: 8800
spring:
  application:
    name: service-trade
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://172.19.1.110:3306/demo
    username: root
    password: fangang12321
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
logging:
  level:
    com.demo.trade: DEBUG